vocab:
  tokenizer:
    vocab: ./wordpiece/mbert_vocab.txt
    lowercase: false
    strip_accents: false
    clean_text: false
  vocab_path: ./vocab.npy

dataset_type:
  name: agnews
  log_dir: ./logs/agnews
  labels: [neg, pos]
  max_seq_len: 128
  dataset_path: None

classification:
  hidden_dim: &hidden_dim 64
  proj_dim: *hidden_dim
  num_class: 4



