vocab:
  tokenizer:
    vocab: ./wordpiece/mbert_vocab.txt
    lowercase: false
    strip_accents: false
    clean_text: false
  vocab_path: ./vocab_new.npy

dataset_type:
  name: hyperpartisan
  log_dir: ./logs/hyperpartisan
  labels: [neg, pos]
  max_seq_len: 2048
  dataset_path: None

classification:
  hidden_dim: &hidden_dim 256
  proj_dim: *hidden_dim
  num_class: 2



