loader:
  batch_size: 500
  num_workers: 1

projection:
  num_hashes: 64
  feature_size: &feature_size 1024
  window_size: &window_size 0

bottleneck:
  window_size: *window_size
  feature_size: *feature_size
  hidden_dim: &hidden_dim 64

backbone:
  index: 7
  hidden_dim: *hidden_dim
  kernel_size: [ 5, 3, 3, 3, 3, 3, 3, 7 ]
  dilation: [ 1, 1, 1, 1, 1, 1, 1, 1 ]
  padding: [ 2, 1, 1, 1, 1, 1, 1, 3 ]
  num_heads: 16
  num_mixers: 2

optimizer:
  lr: 5e-4
  betas: [0.9, 0.999]
  eps: 1e-8

